version: '3.8'

services:
  tigerlogistics-gateway-server:
    container_name: tigerlogistics-gateway-server
    image: manojramakrishnan/tigerlogistics-gateway-server
    ports:
     - '9000:9000'
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://tigerlogistics-discovery-server:8761/eureka
      - management.endpoints.web.exposure.include=*
      # - eureka.instance.preferIpAddress=true
      - SPRING_PROFILES_ACTIVE=dev
      - spring.datasource.url=jdbc:h2:tcp://tigerlogistics-database-service:9550/~/test
      - ribbon.ReadTimeout=60000
      - zuul.host.connect-timeout-millis=60000
      - zuul.host.socket-timeout-millis=60000
      - zuul.sensitiveHeaders=
      - zuul.ignored-headers=Access-Control-Allow-Credentials,Access-Control-Allow-Origins
    depends_on:
      - tigerlogistics-discovery-server
      - tigerlogistics-database-service
  tigerlogistics-discovery-server:
    container_name: inventory-discovery-server
    image: manojramakrishnan/tigerlogistics-discovery-server
    ports:
      - '8761:8761'
    environment:
      - eureka.instance.lease-renewal-interval-in-seconds=30
      - eureka.instance.lease-expiration-duration-in-seconds=90
  inventory-auth-service:
    # container_name: tigerlogistics-auth-service
    image: manojramakrishnan/tigerlogistics-auth-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://tigerlogistics-database-service:9550/~/test
      - SPRING_PROFILES_ACTIVE=dev
      - eureka.client.serviceurl.defaultzone=http://tigerlogistics-discovery-server:8761/eureka
      - eureka.instance.preferIpAddress=true
    restart: always
    depends_on:
      - tigerlogistics-discovery-server
      - tigerlogistics-database-service
  tigerlogistics-rawmaterial-order-service:
    # container_name: tigerlogistics-rawmaterial-order-service
    image: manojramakrishnan/tigerlogistics-rawmaterial-order-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://tigerlogistics-database-service:9550/~/test
      - SPRING_PROFILES_ACTIVE=dev
      - eureka.client.serviceurl.defaultzone=http://tigerlogistics-discovery-server:8761/eureka
      - eureka.instance.preferIpAddress=true
    restart: always
    depends_on:
      - tigerlogistics-discovery-server
      - tigerlogistics-database-service
  inventory-product-order-service:
    # container_name: tigerlogistics-product-order-service
    image: manojramakrishnan/tigerlogistics-product-order-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://tigerlogistics-database-service:9550/~/test
      - SPRING_PROFILES_ACTIVE=dev
      - eureka.client.serviceurl.defaultzone=http://tigerlogistics-discovery-server:8761/eureka
      - eureka.instance.preferIpAddress=true
    restart: always
    depends_on:
      - tigerlogistics-discovery-server
      - tigerlogistics-database-service
  tigerlogistics-stock-management-service:
    # container_name: tigerlogistics-stock-management-service
    image: manojramakrishnan/tigerlogistics-stock-management-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://tigerlogistics-database-service:9550/~/test
      - SPRING_PROFILES_ACTIVE=dev
      - eureka.client.serviceurl.defaultzone=http://tigerlogistics-discovery-server:8761/eureka
      - eureka.instance.preferIpAddress=true
    restart: always
    depends_on:
      - tigerlogistics-discovery-server
      - tigerlogistics-database-service
  tigerlogistics-supplier-service:
    # container_name: tigerlogistics-supplier-service
    image: manojramakrishnan/tigerlogistics-supplier-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://tigerlogistics-database-service:9550/~/test
      - SPRING_PROFILES_ACTIVE=dev
      - eureka.client.serviceurl.defaultzone=http://tigerlogistics-discovery-server:8761/eureka
      - eureka.instance.preferIpAddress=true
    restart: always
    depends_on:
      - tigerlogistics-discovery-server
      - tigerlogistics-database-service
  tigerlogistics-database-service:
    container_name: tigerlogistics-database-service
    image: manojramakrishnan/tigerlogistics-database-service
    restart: always
    depends_on:
      - tigerlogistics-discovery-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:~/test
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://tigerlogistics-discovery-server:8761/eureka
  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: Watchtower
  #   restart: unless-stopped
  #   network_mode: bridge
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   # Name here must be same as container_name
  #   command: tigerlogistics-gateway-service tigerlogistics-discovery-server tigerlogistics-h2-service tigerlogistics-auth-service --cleanup true --debug
  #   environment:
  #     - TZ=Asia/Kolkata
  #     - WATCHTOWER_POLL_INTERVAL=240
# Execute using  docker-compose up --remove-orphans -d
# Dcaling
# docker-compose -f docker-compose.dev.yml scale tigerlogistics-auth-service=3

