apiVersion: apps/v1

kind: Deployment

metadata:

  name: eureka-deployment

spec:

  replicas: 1

  selector:

    matchLabels:

      app: eureka

  template:

    metadata:

      labels:

        app: eureka

    spec:

      containers:

        - name: eureka

          image: manojramakrishnan/tigerlogistics-discovery-server

          resources:

            limits:

              memory: '200Mi'

              cpu: '250m'

          env:

            - name: eureka.instance.lease-renewal-interval-in-seconds

              value: '30'

            - name: eureka.instance.lease-expiration-duration-in-seconds

              value: '90'

 

---

apiVersion: v1

kind: Service

metadata:

  name: tigerlogistics-discovery-server

spec:

  selector:

    app: eureka

  ports:

    - name: eureka-srv-clusterip-port

      protocol: TCP

      port: 8761

      targetPort: 8761

 