name: Docker push - Frontend

on:
  push:
    branches:
      - dev
    paths:
      - 'tigerlogistics-frontend/**'
defaults:
  run:
    working-directory: tigerlogistics-frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Make a production build
        run: |
          npm install -g @angular/cli@10
          npm install
          ng build --prod --base-href="/"
      - name: Set env
        run: echo "NOW=v$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV
        # Required for Build and push step
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        # Required for Build and push step
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        # Required for Build and push step
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: tigerlogistics-frontend
          file: tigerlogistics-frontend/Dockerfile
          push: true
          tags: |
            manojramakrishnan/frontend-frontend:${{env.NOW}}
            manojramakrishnan/frontend-frontend:latest